# Generated by Django 3.0.6 on 2020-05-21 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_topic_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='solution',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='message',
            field=models.TextField(blank=True),
        ),
    ]
